version: "3.7"

services:
  # Dremio
  dremio:
    platform: linux/x86_64
    image: dremio/dremio-oss:latest
    ports:
      - 9047:9047
      - 31010:31010
      - 32010:32010
    container_name: dremio
    environment:
      - DREMIO_JAVA_SERVER_EXTRA_OPTS=-Dpaths.dist=file:///opt/dremio/data/dist
    networks:
      dremio-superset:
  #Superset
  superset:
    build:
      context: ./superset
      dockerfile: Dockerfile
    container_name: superset
    volumes:
      - ./scripts:/home/superset/custom_scripts
    networks:
      dremio-superset:
    ports:
      - 8080:8088
networks:
  dremio-superset: